---
- name: Download the latest kubectl release
  uri:
    url: https://dl.k8s.io/release/{{ kubectl_version }}/bin/linux/{{ arch }}/kubectl
    dest: /home/{{ ansible_user }}
  register: kubectl

- name: Download the kubectl checksum file
  uri:
    url: https://dl.k8s.io/{{ kubectl_version }}/bin/linux/{{ arch }}/kubectl.sha256
    dest: /home/{{ ansible_user }}

- name: Validate the kubectl binary against the checksum file
  shell: echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check
  register: result

- name: Assert that the kubectl binary is OK
  vars:
    expected: "kubectl: OK"
  assert:
    that:
      - result.stdout == expected
    fail_msg: "{{ result.stdout }}"
    success_msg: "{{ result.stdout }}"

# TODO: Should tolerate existing file
- name: Move kubectl and change permissions
  file:
    src: "{{ kubectl.path }}"
    dest: /usr/local/bin/kubectl
    state: hard
    owner: root
    group: root
    mode: "+x"
  become: true

- name: Check if kubectl is installed
  shell: kubectl version --client
  register: client
  failed_when: client.rc > 1

# TODO: Cleanup
...
