---
# https://docs.ansible.com/ansible/2.9/modules/openssl_certificate_module.html


# - openssl_privatekey_info:
#     path: /etc/ssl/csr/ansible.com.key
#   register: result_privatekey

- name: Copy bandmaster public key
  ansible.builtin.copy:
    src: bandmaster.pub
    dest: /home/vagrant/bandmaster.pub
    owner: vagrant
    group: vagrant
    mode: '0644'

- name: Add public key to authorized_keys
  authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ lookup('file', 'bandmaster.pub') }}"
    path: /home/{{ ansible_user }}/.ssh/authorized_keys
    manage_dir: false

...